[package]
name = "crisi/jojocom"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
promise = "evaera/promise@4.0.0"
signal = "sleitnick/signal@1.2.1"